-- Mod custom strings
local STRINGS = GLOBAL.STRINGS

-- World objects
STRINGS.CHARACTERS.WX78.DESCRIBE.GEOTHERMAL_VENT = "HEAT SOURCE DETECTED."
STRINGS.CHARACTERS.WX78.DESCRIBE.CRABHOLE = "CRAB SOURCE DETECTED."
STRINGS.CHARACTERS.WX78.DESCRIBE.UNDERWATER_ENTRANCE = {GENERIC = "MINING THIS WITH A PICKAXE WILL BE ENOUGH TO UN-BLOCK THE ENTRANCE.", OPEN = "I SHOULD DESCEND FOR ANALYSIS."}
STRINGS.CHARACTERS.WX78.DESCRIBE.MERMNOBLEHOUSE = "THIS ABODE HAS BEEN UPDATED TO ITS LATEST VERSION."
STRINGS.CHARACTERS.WX78.DESCRIBE.MERMWORKERHOUSE = "IT PROVIDES THE UPDATES FOR THIS VILLAGE AND ITS INHABITANTS."
STRINGS.CHARACTERS.WX78.DESCRIBE.MERMGUARDHOUSE = "THIS VILLAGE'S ANTI-VIRUS."
STRINGS.CHARACTERS.WX78.DESCRIBE.ROTTING_TRUNK = "A ROTTING PIECE OF TRUNK. \nIT IS IRRELEVANT TO ME."
STRINGS.CHARACTERS.WX78.DESCRIBE.SUNKEN_CHEST = "UNDERWATER STORAGE UNIT DETECTED."
STRINGS.CHARACTERS.WX78.DESCRIBE.SEAGRASS =
{
	GENERIC = "ONLY IMPERMEABLE FIRE WOULD BE ABLE TO COMBUST THIS.",
	PICKED = "IT WILL GROW BACK SOON. \nIT'S CURRENTLY IN A LOOPING STAGE.",
}
STRINGS.CHARACTERS.WX78.DESCRIBE.DEPLETED_SEAGRASS = "AN EXPIRED TUFT OF SEAGRASS."
STRINGS.CHARACTERS.WX78.DESCRIBE.UW_CORAL = "IT DAMAGES MY MOBILE UNIT."
STRINGS.CHARACTERS.WX78.DESCRIBE.FLOWER_SEA = "PRETTY ENOUGH FOR ME TO APPRECIATE IT."
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDSTONE_BOULDER = "100% MINE-ABLE."
STRINGS.CHARACTERS.WX78.DESCRIBE.IRON_BOULDER = "MINING SYSTEMS: ACTIVATE."
STRINGS.CHARACTERS.WX78.DESCRIBE.UW_CORAL_BLUE = "SHARP CORALS"
STRINGS.CHARACTERS.WX78.DESCRIBE.UW_CORAL_GREEN = "SHARP CORALS"
STRINGS.CHARACTERS.WX78.ANNOUNCE_OUT_OF_OXYGEN = "BREATHING MODULE FLOODED"--gonna go unused, oh well
STRINGS.CHARACTERS.WX78.DESCRIBE.SPONGE = "ABSORBENT PLANT"
STRINGS.CHARACTERS.WX78.DESCRIBE.DECORATIVE_SHELL = "A SEASHELL FOUND UNDER THE SEASHORE"
STRINGS.CHARACTERS.WX78.DESCRIBE.BUBBLE_VENT = "AIR VENT FOR INFERIOR FLESHLINGS"
STRINGS.CHARACTERS.WX78.DESCRIBE.SEAQUAKETENTACLE = "THIS UNIT HAS SUCTION ADD-ONS"
STRINGS.CHARACTERS.WX78.DESCRIBE.KELP = "KELP STALK GETS EASILY TANGLED IN MY SERVOS"


-- Craftable items
STRINGS.CHARACTERS.WX78.DESCRIBE.HAT_DIVING = "BREATHING IS NOT A PROBLEM FOR ME. \nMAKING THIS WAS IRRELEVANT."
STRINGS.CHARACTERS.WX78.DESCRIBE.HAT_SNORKEL = "WHY DID I MAKE THIS? \nTHIS ACTION WAS IRRELEVANT AND IRRATIONAL."
STRINGS.CHARACTERS.WX78.DESCRIBE.PEARL_AMULET = "MY SENSORS SAY THIS AMULET IS USELESS."
STRINGS.CHARACTERS.WX78.DESCRIBE.FLARE = "TECHNOLOGY PREVAILS ONCE AGAIN."
STRINGS.CHARACTERS.WX78.DESCRIBE.DIVING_SUIT_SUMMER = "IT PROTECTS MY BODY UNIT FROM THE WATER."
STRINGS.CHARACTERS.WX78.DESCRIBE.DIVING_SUIT_WINTER = "IT PROTECTS MY BODY UNIT FROM THE WATER AND KEEPS ITS TEMPERATURE AT A WARM LEVEL."
STRINGS.CHARACTERS.WX78.DESCRIBE.JELLY_LANTERN = "MEATBAG MADE TO SHINE BEYOND ITS NATURAL PREDISPOSITIONS"
STRINGS.CHARACTERS.WX78.DESCRIBE.CORAL_CLUSTER = "OPEN SOURCE CORAL"


-- Inventory items
STRINGS.CHARACTERS.WX78.DESCRIBE.PEARL = "MY BEAUTY APPRECIATOR IS LIMITED. \nI CAN'T APPREACIATE THIS."
STRINGS.CHARACTERS.WX78.DESCRIBE.CORAL_PIECES = "WHAT IS THE USE OF THIS OBJECT?"
STRINGS.CHARACTERS.WX78.DESCRIBE.SANDSTONE = "WHAT COULD I MAKE WITH THIS? \nGLASS?"
STRINGS.CHARACTERS.WX78.DESCRIBE.IRON_ORE = "MINING SYSTEMS ARE WORKING PERFECTLY."
STRINGS.CHARACTERS.WX78.DESCRIBE.SEAGRASS_CHUNK = "STUPID FLESHLINGS WRAP DEAD FISH AND RICE IN THIS"
STRINGS.CHARACTERS.WX78.DESCRIBE.CUT_ORANGE_CORAL = "RESISTANCE IS FUTILE, YOU LOST ANYWAY"
STRINGS.CHARACTERS.WX78.DESCRIBE.CUT_BLUE_CORAL = "RESISTANCE IS FUTILE, YOU LOST ANYWAY"
STRINGS.CHARACTERS.WX78.DESCRIBE.CUT_GREEN_CORAL = "RESISTANCE IS FUTILE, YOU LOST ANYWAY"
STRINGS.CHARACTERS.WX78.DESCRIBE.SPONGE_PIECE = "ABSORBENT RECTANGULAR ITEM"
STRINGS.CHARACTERS.WX78.DESCRIBE.BUBBLE_ITEM = "MY BREATHING MODULE DOES NOT REQUIRE REFILLS"
STRINGS.CHARACTERS.WX78.DESCRIBE.LAVASTONE = "HEATED STONE"
STRINGS.CHARACTERS.WX78.DESCRIBE.JELLY_CAP = "THIS CAP IS NOT FOR WEARING"
STRINGS.CHARACTERS.WX78.DESCRIBE.SALT = "SALT WATER CORRODES MY SERVOS"


-- Monsters
STRINGS.CHARACTERS.WX78.DESCRIBE.REEF_JELLYFISH = "BASICALLY WATER IN A MOBILE UNIT."
STRINGS.CHARACTERS.WX78.DESCRIBE.SQUID = "ITS DEFENSE SYSTEM IS BETTER THAN MINE."
STRINGS.CHARACTERS.WX78.DESCRIBE.CRAB = "CRABS ARE NOT SMART CREATURES."
STRINGS.CHARACTERS.WX78.DESCRIBE.MERMNOBLE = "THEY HAVE THE LATEST RELEASED UPDATE PATCH. \nTHEY'RE ABOVE-GROUND COUNTERPARTS ARE STILL IN ALPHA."
STRINGS.CHARACTERS.WX78.DESCRIBE.MERMWORKER = "THEY RELEASE THE UPDATE PATCHES FOR THIS VILLAGE."
STRINGS.CHARACTERS.WX78.DESCRIBE.MERMGUARD = "THE ANTI-VIRUS MUST BE DOING A CHECK-UP."
STRINGS.CHARACTERS.WX78.DESCRIBE.SEATENTACLE = "I KEEP MY STATEMENT. \nBIOLOGY IS DISGUSTING."
STRINGS.CHARACTERS.WX78.DESCRIBE.COMMONFISH = "AQUATIC MEAT"
STRINGS.CHARACTERS.WX78.DESCRIBE.CLAM = "UNIT HAS A DEFENSE MECHANISM FOR THE PEARL"
STRINGS.CHARACTERS.WX78.DESCRIBE.SEA_EEL = "AQUATIC UNIT RUNS ON ELECTRICITY?"
STRINGS.CHARACTERS.WX78.DESCRIBE.WORMPLANT = "UNITS HIDE FROM MY PRESENCE. HA HA."
STRINGS.CHARACTERS.WX78.DESCRIBE.SHRIMP = "YES, COWER IN FEAR! HA HA HA"

-- Edible
STRINGS.CHARACTERS.WX78.DESCRIBE.SEAJELLY = "IT TASTES BETTER THAN IT LOOKS"
STRINGS.CHARACTERS.WX78.DESCRIBE.FISH_FILLET = "FISH FLAVORED FUEL"
STRINGS.CHARACTERS.WX78.DESCRIBE.FISH_FILLET_COOKED = "COOKED FISH FUEL"
STRINGS.CHARACTERS.WX78.DESCRIBE.TENTACLE_SUSHI = "SUSHI IS SUSHI"
STRINGS.CHARACTERS.WX78.DESCRIBE.SHRIMP_TAIL = "A LESSON TO SHRIMPETS EVERYWHERE"
STRINGS.CHARACTERS.WX78.DESCRIBE.SEA_CUCUMBER = "A SPIKY CUCUMBER. MAY MAKE A DECENT ALLY"
STRINGS.CHARACTERS.WX78.DESCRIBE.FISH_GAZPACHO = "CHILLED VEGETABLE FUEL "
STRINGS.CHARACTERS.WX78.DESCRIBE.TUNA_MUFFIN = "A LARGE, FISH-BASED MUFFIN"

-- New strings

STRINGS.CHARACTERS.WX78.DESCRIBE.SEA_PETALS = "HOW DISGUSTINGLY ATTRACTIVE"
STRINGS.CHARACTERS.WX78.DESCRIBE.UW_FLOWERS = "AQUATIC FLOWER"
STRINGS.CHARACTERS.WX78.DESCRIBE.UNDERWATER_EXIT = "MY SERVOS NEED DRAINING"